language: rust
sudo: false

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    secure: aa3KwhwOTko0kDf7cbxa2ADbPihtvMnZsbIi/GFzNYVqLeLTWAuSph3uLzJACP9auitpOxIzvYvTGm4Btck1khwclOBR1dzZ6GKxvMjiW9ln9bCRV1rim+68ESdLHTRftJOkvzwX5tcLaBO5ib9RGNTe7wPBZdT4Q9NPuTJAyjvafhYvvtrZGwxmlNYWFzSooPHPYLb4CU/ffuxKFXfOCjlYU1W6FhQhrSzURTnVcIvW+zwVtqiJcVRbQkO+RZ+NY3c1MR4JMap3H9/MPO5Ff6+vjC1gLuAj9OocqgOWKvMXFL570mSIfSKn6KWPZf93xIGh7Y/BTiqi5jGZffZ1TWGv1xLOFGfN5FrWUzjb2l3hALHBv1te8TJnAHcEjSFTVOngvWR9lpblxpPZQWK5aC1noBA0JUFrk/9Xowk335SK4M0IViAERH7yXMJRah4bMSMEGvcs6KQmEq8u00fHz4hXXjbQpOXDoKRAdIwtwiZAE8N253xK36bew+TfQaDjh6xDcGMhuO09yyaryEl1fYpeoWmQ4qLIVURTl1i202OkeoLqPucCzz1GWX20UdWsVh9HVALxeFcGQtGbEEzKwzBr4OvJBmuet78rc1aB9Uv8u8me1m0vd/o2PmvPREu7ajVm6+Bk9/W96vtmK0CqkrGmzw5G90LOwUkXok+anzU=

notifications:
  email: false
