[package]
name = "sqlite"
version = "0.6.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/sqlite"
homepage = "https://github.com/stainless-steel/sqlite"
documentation = "https://stainless-steel.github.io/sqlite"
description = "The package provides an interface to SQLite."

[dependencies]
libc = "*"
sqlite3-sys = "*"

[dev-dependencies]
temporary = "*"
