[package]
name = "sqlite"
version = "0.14.2"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/sqlite"
homepage = "https://github.com/stainless-steel/sqlite"
documentation = "https://stainless-steel.github.io/sqlite"
description = "The package provides an interface to SQLite."
build = "build.rs"

[dependencies]
libc = "*"
sqlite3-sys = "0.6"

[dev-dependencies]
temporary = "*"
