[package]
name = "sqlite"
version = "0.20.0"
license = "Apache-2.0/MIT"
authors = [
  "Ivan Ukhov <ivan.ukhov@gmail.com>",
  "Jake Kerr <kodafox@gmail.com>",
  "Tomoki Aonuma <uasi@uasi.jp>",
]
description = "The package provides an interface to SQLite."
documentation = "https://stainless-steel.github.io/sqlite"
homepage = "https://github.com/stainless-steel/sqlite"
repository = "https://github.com/stainless-steel/sqlite"

[dependencies]
libc = "0.2"
sqlite3-sys = "0.6"

[dev-dependencies]
temporary = "0.5"

[features]
# Link sqlite3-sys against sqlcipher, instead of sqlite3,
# enabling support for transparent database encryption.
sqlcipher = ["sqlite3-sys/sqlcipher"]
