[package]
name = "sqlite"
version = "0.14.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/sqlite"
homepage = "https://github.com/stainless-steel/sqlite"
documentation = "https://stainless-steel.github.io/sqlite"
description = "The package provides an interface to SQLite."

[features]
edge = ["sqlite3-sys/edge"]

[dependencies]
libc = "*"
sqlite3-sys = "*"

[dev-dependencies]
temporary = "*"
